////
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
////
This repository contains an initial sketch of an *Apache Logging Admin API*.
See the ["New API for log level manipulation" thread](https://lists.apache.org/thread/ktdlo5br6jc39xo33vdsfsj2s200mm93) for more details.

The purpose of the API is to allow the programmatic configuration of the logging backend in an implementation independent way.

[source,java]
----
import org.apache.logging.admin.LoggingAdmin;

public final class Main {
  private static final Object TOKEN = new Object();

  public static void main(String[] args) {
    int i = 0;
    while (i < args.length) {
      if ("--logLevel".equals(args[i]) && ++i < args.length) {
        LoggingAdmin admin = LoggingAdmin.getInstance(TOKEN);
        admin.setLevel("", args[i]);
      }
      i++;
    }
  }
}
----
